### ISSUE TITLE
Incorrectly adding paths

### ISSUE THREAD

**Issue by uw-adcs-krish** [uw-adcs-krish/uw_cubesat_adcs#2]
https://github.com/uw-adcs-krish/uw_cubesat_adcs/blob/9dc22af9628e1dfcf8b19b28e9a051cfb78a5ede/adcs/sw/components/adcs_sim/matlab/sim_init.m#L15

@tpreynolds - For the above lines of code, you cannot use the ~ symbol for Windows machines. All the paths should be added relative to your current working directory, i.e.,
`addpath(genpath('../../adcs_fsw'))`
`addpath(genpath('../../adcs_bdot'))`
`addpath(genpath('../../adcs_sim'))`

You also don't need to `cd` into the directory that you want to add to path. You can do it all relative to the one your currently in via the above commands.

**Comment by tpreynolds** [comment]
fixed this a while ago.
