### ISSUE TITLE
**GPS**

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#24]
Secondary software test for this library. Refers to the actual GPS sensor model located in the sensor library, not the GPS_time generator located in environment.

**Comment by uw-adcs-krish** [comment]
- Replace ZOHs with rate transitions on input / output
  - Make sample time a config parameter
- Put ecef2eci transpose inside subsystem block
- Label gain block name as the variable
- Why have number of sats as a constant? It isn't used anywhere else in the Sim
  - Use transport delay on pulse generator and then detect-increase for emulating lock time for GPS
- Put the time constants into the constant struct and pull that into the matlab function
  - This allows us to do config / constant reviews from the top level
- Output jd_utc time from time_conversions as well as ut1
- In coordinate_rotations, get rid of deprecated code - don't just leave as comments
  - Add constants into struct and pull into matlab embedded function
- Make lookup table for dUT1 and don't put dUT1 in bus struct - make a time struct

**Comment by tpreynolds** [comment]
Have verified the library with Vallado Ex 3-15. Add a comment in the library function that says it was verified.

**Comment by tpreynolds** [comment]
Pulling fsw_params into matlab functions is causing (all model files) to crash upon building. I have a few examples for the time and coord rotations library, but am going to skip this for now until we can look at it.

**Comment by tpreynolds** [comment]
Ive made the other simpler changes from here. Have not made dUT1 a look up table yet.
