### ISSUE TITLE
**SGP4 Orbit Propagator**

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#25]
Secondary software test for this library.

**Comment by uw-adcs-krish** [comment]
* Put in hooks to catch orbital degeneracies like ecc >= 1, ecc == 0
  * Add unit tests for these as well
* Add unit test for low altitude case
* Reduce number of iterations for solving Kepler's equation to like 10 and make a for-loop
  * Log the iteration number for a few cases and pick an upper bound
  * 1000 is way too high!
* Add unit test that exercises all if-conditions (if not captured by the above tests)
* UT1 is being passed into SGP4 in the top level MSP_FSW - it needs to be UTC
* Put rate transitions inside the library, not at top-level FSW
  * This is an issue for LOTS of libraries in FSW
* Already been compared against STK and Vallado, so I'm not going to check that
* 7.5 km drift over 3 days is not great - what is your hypothesis for this?
* Vallado test (3) has lots of position / velocity error - what's going on here?
* Put teme_2_eci conversions inside the library

**Comment by tpreynolds** [comment]
So far have changed:
- Passed UTC time to the library.
- Updated library so that ECI inertial vectors are passed out, math for conversion from TEME is done inside the library.
- Updated the test library to reflect new changes to time/coord rotation and SGP4 libraries.
- Dropped iterations in Kepler to 10 and checked that it had no impact on performance vs. STK. Can check that it doesn't (often) hit this u.b. with more testing.
**Note:** I changed the env_estimation, gs_prediction and mag_vec libraries to eliminate the math done in the higher level library env_estimation.

I'm not seeing the 7.5 km drift. Tests 1 and 2 show drift on the order of 1m over 3 days.

Still need to double check the Vallado example. No thoughts yet on why this is so off.

Will add in validity checks for ecc, and divide by zero conditions and add unit tests for these ... likely in sprint 18.

**Comment by tpreynolds** [comment]
Added hooks for ecc, mean motion, and other divide by zero conditions. Added a unit test for all orbital element checks and low altitude.
