### ISSUE TITLE
EKF Quaternion Not Equal to the State Quaternion

### ISSUE THREAD

**Issue by scrice** [uw-adcs-krish/uw_cubesat_adcs#58]
Running a full system test, I noticed a significant difference between the quaternion estimated out of the EKF and the quaternion coming out of the dynamics. This needs to be resolved such that the spacecraft points where we think it is pointing.

**Comment by MathiasKerman** [comment]
Can you provide some details? What happens if you initialize the estimate and the spacecraft attitude with the same quaternion?

**Comment by tpreynolds** [comment]
Traced the issue back to commit 6019d362. Reverted origin/develop to the last working state before that and then added changes sequentially. We do not see this error anymore, but not sure what part of the commit caused it.
