### ISSUE TITLE
**Ground Track Visualization**

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#8]
Creating a simulink based method of visualizing our ground track (projected onto Earth) in real time when we run the sim. Should be created as a standalone library so it can be omitted during autocoding.

**Comment by scrice** [comment]
There is still a line going across the image when the longitude goes from -180 to 180. I can't come up with a clear fix for this and it isn't a major issue, just looks a little less clean than would be ideal.
