### ISSUE TITLE
**Magnetic Field Vector**

### ISSUE THREAD

**Issue by tpreynolds** [uw-adcs-krish/uw_cubesat_adcs#9]
Secondary software test of this library.

**Comment by e-vic** [comment]
secondary test complete - difference between calculated magnetic field and reference magnetic field from https://www.ngdc.noaa.gov/geomag-web/#igrfwmm for alt 500km is ~10nT, seems reasonable. difference for reference from http://geomag.nrcan.gc.ca/calc/mfcal-en.php for alt 0.45km (about sea level) is ~2nT
